services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/migrations/init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - ./server/migrations/002-align-existing-schema.sql:/docker-entrypoint-initdb.d/002_align_existing_schema.sql
      - ./server/migrations/003_create_sensors_and_audit.sql:/docker-entrypoint-initdb.d/003_create_sensors_and_audit.sql
      - ./server/migrations/004_create_login_attempts.sql:/docker-entrypoint-initdb.d/004_create_login_attempts.sql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server/logs:/app/logs
      - ./server/src:/app/src

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: